version: '4.37'

services:
 postgres:
  image: bitnami/postgresql
  container_name: task_management
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}